apiVersion: apps/v1
kind: Deployment
metadata:
  name: study
spec:
  selector:
    matchLabels:
      app: study
  replicas: 1
  template:
    metadata:
      labels:
        app: study
    spec:
      containers:
      - image: harbor.ksign.com/study/study:latest
        name: study
        imagePullSecrets:
        - name: regcred
        ports:
        - containerPort: 4885