apiVersion: v1
kind: Service
metadata:
  name: study
  labels:
    app: study
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4885
      targetPort: 4885
  selector:
    app: study